server:
  port: 8080
spring:
  application:
    name: game-service
  r2dbc: 
    url: r2dbc:postgresql://localhost:5432/slitherdb
    username: slither
    password: slither123
  datasource:
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
