name: Muilti-Service CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: slitherdb
          POSTGRES_USER:  slither
          POSTGRES_PASSWORD: slither123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do
            sleep 1
          done
      
      # Build a test para game-service
      - name: Build and Test game-service
        working-directory: ./game-service
        env:
          SPRING_R2DBC_URL: r2dbc:postgresql://localhost:5432/slitherdb
          SPRING_R2DBC_USERNAME: slither
          SPRING_R2DBC_PASSWORD: slither123
        run: ./gradlew build
